// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployproto.proto

package deployproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeployMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Domain               string   `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Cenv                 string   `protobuf:"bytes,5,opt,name=cenv,proto3" json:"cenv,omitempty"`
	ProjectID            string   `protobuf:"bytes,6,opt,name=projectID,proto3" json:"projectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployMessage) Reset()         { *m = DeployMessage{} }
func (m *DeployMessage) String() string { return proto.CompactTextString(m) }
func (*DeployMessage) ProtoMessage()    {}
func (*DeployMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e818a39b64e3e2b, []int{0}
}

func (m *DeployMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployMessage.Unmarshal(m, b)
}
func (m *DeployMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployMessage.Marshal(b, m, deterministic)
}
func (m *DeployMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployMessage.Merge(m, src)
}
func (m *DeployMessage) XXX_Size() int {
	return xxx_messageInfo_DeployMessage.Size(m)
}
func (m *DeployMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeployMessage proto.InternalMessageInfo

func (m *DeployMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployMessage) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeployMessage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DeployMessage) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DeployMessage) GetCenv() string {
	if m != nil {
		return m.Cenv
	}
	return ""
}

func (m *DeployMessage) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

type DeployStatusMessage struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Runningversion       string   `protobuf:"bytes,2,opt,name=runningversion,proto3" json:"runningversion,omitempty"`
	Other                string   `protobuf:"bytes,3,opt,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployStatusMessage) Reset()         { *m = DeployStatusMessage{} }
func (m *DeployStatusMessage) String() string { return proto.CompactTextString(m) }
func (*DeployStatusMessage) ProtoMessage()    {}
func (*DeployStatusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e818a39b64e3e2b, []int{1}
}

func (m *DeployStatusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployStatusMessage.Unmarshal(m, b)
}
func (m *DeployStatusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployStatusMessage.Marshal(b, m, deterministic)
}
func (m *DeployStatusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployStatusMessage.Merge(m, src)
}
func (m *DeployStatusMessage) XXX_Size() int {
	return xxx_messageInfo_DeployStatusMessage.Size(m)
}
func (m *DeployStatusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployStatusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeployStatusMessage proto.InternalMessageInfo

func (m *DeployStatusMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DeployStatusMessage) GetRunningversion() string {
	if m != nil {
		return m.Runningversion
	}
	return ""
}

func (m *DeployStatusMessage) GetOther() string {
	if m != nil {
		return m.Other
	}
	return ""
}

type DeployResponse struct {
	Success              string   `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployResponse) Reset()         { *m = DeployResponse{} }
func (m *DeployResponse) String() string { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()    {}
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e818a39b64e3e2b, []int{2}
}

func (m *DeployResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResponse.Unmarshal(m, b)
}
func (m *DeployResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResponse.Marshal(b, m, deterministic)
}
func (m *DeployResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResponse.Merge(m, src)
}
func (m *DeployResponse) XXX_Size() int {
	return xxx_messageInfo_DeployResponse.Size(m)
}
func (m *DeployResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResponse proto.InternalMessageInfo

func (m *DeployResponse) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

func init() {
	proto.RegisterType((*DeployMessage)(nil), "deployproto.DeployMessage")
	proto.RegisterType((*DeployStatusMessage)(nil), "deployproto.DeployStatusMessage")
	proto.RegisterType((*DeployResponse)(nil), "deployproto.DeployResponse")
}

func init() { proto.RegisterFile("deployproto.proto", fileDescriptor_7e818a39b64e3e2b) }

var fileDescriptor_7e818a39b64e3e2b = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x5d, 0x6d, 0x57, 0x3a, 0xda, 0x82, 0xa3, 0x94, 0x50, 0x3c, 0x94, 0x3d, 0x88, 0x78,
	0x28, 0xa2, 0xaf, 0xd0, 0x8b, 0x07, 0x0f, 0x56, 0x5f, 0x20, 0xa6, 0xc3, 0x1a, 0xb5, 0x49, 0xc8,
	0x64, 0x0b, 0x3e, 0x90, 0xef, 0x29, 0x9b, 0x6c, 0xb4, 0x2b, 0xbd, 0xec, 0xce, 0xff, 0xff, 0x81,
	0xff, 0x9b, 0x04, 0xce, 0xd6, 0xe4, 0x3e, 0xed, 0x97, 0xf3, 0x36, 0xd8, 0x45, 0xfc, 0xe2, 0xc9,
	0x8e, 0x55, 0x7d, 0x17, 0x30, 0x5e, 0x46, 0xfd, 0x48, 0xcc, 0xb2, 0x26, 0x44, 0x18, 0x18, 0xb9,
	0x21, 0x51, 0xcc, 0x8b, 0xeb, 0xd1, 0x2a, 0xce, 0x78, 0x09, 0xa3, 0xf6, 0xcf, 0x4e, 0x2a, 0x12,
	0x87, 0x31, 0xf8, 0x33, 0x50, 0xc0, 0xf1, 0x96, 0x3c, 0x6b, 0x6b, 0xc4, 0x51, 0xcc, 0xb2, 0xc4,
	0x29, 0x94, 0x6b, 0xbb, 0x91, 0xda, 0x88, 0x41, 0x0c, 0x3a, 0xd5, 0x76, 0x28, 0x32, 0x5b, 0x31,
	0x4c, 0x1d, 0xed, 0xdc, 0x76, 0x38, 0x6f, 0xdf, 0x49, 0x85, 0x87, 0xa5, 0x28, 0x53, 0xc7, 0xaf,
	0x51, 0x7d, 0xc0, 0x79, 0xc2, 0x7c, 0x0e, 0x32, 0x34, 0x9c, 0x61, 0xa7, 0x50, 0x72, 0x34, 0x3a,
	0xdc, 0x4e, 0xe1, 0x15, 0x4c, 0x7c, 0x63, 0x8c, 0x36, 0x75, 0x26, 0x4b, 0xd4, 0xff, 0x5c, 0xbc,
	0x80, 0xa1, 0x0d, 0x6f, 0xe4, 0x3b, 0xf0, 0x24, 0xaa, 0x1b, 0x98, 0xa4, 0xb2, 0x15, 0xb1, 0xb3,
	0x86, 0xe3, 0x8a, 0xdc, 0x28, 0x45, 0x9c, 0x8b, 0xb2, 0xbc, 0x93, 0x70, 0x9a, 0xce, 0x6a, 0x23,
	0x83, 0xf5, 0xf8, 0x04, 0xe3, 0x17, 0xaf, 0xeb, 0x9a, 0x7c, 0xb2, 0x71, 0xb6, 0xd8, 0x7d, 0x82,
	0xde, 0x5d, 0xcf, 0xe6, 0x7b, 0xb2, 0xde, 0x82, 0xd5, 0xc1, 0x6d, 0xf1, 0x5a, 0xc6, 0xf8, 0xfe,
	0x27, 0x00, 0x00, 0xff, 0xff, 0xab, 0x9d, 0xa7, 0x7e, 0xcc, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeployinatorClient is the client API for Deployinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeployinatorClient interface {
	TriggerDeploy(ctx context.Context, in *DeployMessage, opts ...grpc.CallOption) (Deployinator_TriggerDeployClient, error)
}

type deployinatorClient struct {
	cc *grpc.ClientConn
}

func NewDeployinatorClient(cc *grpc.ClientConn) DeployinatorClient {
	return &deployinatorClient{cc}
}

func (c *deployinatorClient) TriggerDeploy(ctx context.Context, in *DeployMessage, opts ...grpc.CallOption) (Deployinator_TriggerDeployClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Deployinator_serviceDesc.Streams[0], "/deployproto.Deployinator/TriggerDeploy", opts...)
	if err != nil {
		return nil, err
	}
	x := &deployinatorTriggerDeployClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Deployinator_TriggerDeployClient interface {
	Recv() (*DeployStatusMessage, error)
	grpc.ClientStream
}

type deployinatorTriggerDeployClient struct {
	grpc.ClientStream
}

func (x *deployinatorTriggerDeployClient) Recv() (*DeployStatusMessage, error) {
	m := new(DeployStatusMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DeployinatorServer is the server API for Deployinator service.
type DeployinatorServer interface {
	TriggerDeploy(*DeployMessage, Deployinator_TriggerDeployServer) error
}

// UnimplementedDeployinatorServer can be embedded to have forward compatible implementations.
type UnimplementedDeployinatorServer struct {
}

func (*UnimplementedDeployinatorServer) TriggerDeploy(req *DeployMessage, srv Deployinator_TriggerDeployServer) error {
	return status.Errorf(codes.Unimplemented, "method TriggerDeploy not implemented")
}

func RegisterDeployinatorServer(s *grpc.Server, srv DeployinatorServer) {
	s.RegisterService(&_Deployinator_serviceDesc, srv)
}

func _Deployinator_TriggerDeploy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeployMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeployinatorServer).TriggerDeploy(m, &deployinatorTriggerDeployServer{stream})
}

type Deployinator_TriggerDeployServer interface {
	Send(*DeployStatusMessage) error
	grpc.ServerStream
}

type deployinatorTriggerDeployServer struct {
	grpc.ServerStream
}

func (x *deployinatorTriggerDeployServer) Send(m *DeployStatusMessage) error {
	return x.ServerStream.SendMsg(m)
}

var _Deployinator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "deployproto.Deployinator",
	HandlerType: (*DeployinatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TriggerDeploy",
			Handler:       _Deployinator_TriggerDeploy_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "deployproto.proto",
}
