// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployproto.proto

package deployproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeployMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Domain               string   `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Cenv                 string   `protobuf:"bytes,5,opt,name=cenv,proto3" json:"cenv,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Summary              string   `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	Enabled              string   `protobuf:"bytes,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployMessage) Reset()         { *m = DeployMessage{} }
func (m *DeployMessage) String() string { return proto.CompactTextString(m) }
func (*DeployMessage) ProtoMessage()    {}
func (*DeployMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e818a39b64e3e2b, []int{0}
}

func (m *DeployMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployMessage.Unmarshal(m, b)
}
func (m *DeployMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployMessage.Marshal(b, m, deterministic)
}
func (m *DeployMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployMessage.Merge(m, src)
}
func (m *DeployMessage) XXX_Size() int {
	return xxx_messageInfo_DeployMessage.Size(m)
}
func (m *DeployMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeployMessage proto.InternalMessageInfo

func (m *DeployMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployMessage) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DeployMessage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DeployMessage) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DeployMessage) GetCenv() string {
	if m != nil {
		return m.Cenv
	}
	return ""
}

func (m *DeployMessage) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DeployMessage) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *DeployMessage) GetEnabled() string {
	if m != nil {
		return m.Enabled
	}
	return ""
}

type DeployResponse struct {
	Success              string   `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployResponse) Reset()         { *m = DeployResponse{} }
func (m *DeployResponse) String() string { return proto.CompactTextString(m) }
func (*DeployResponse) ProtoMessage()    {}
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e818a39b64e3e2b, []int{1}
}

func (m *DeployResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployResponse.Unmarshal(m, b)
}
func (m *DeployResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployResponse.Marshal(b, m, deterministic)
}
func (m *DeployResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployResponse.Merge(m, src)
}
func (m *DeployResponse) XXX_Size() int {
	return xxx_messageInfo_DeployResponse.Size(m)
}
func (m *DeployResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeployResponse proto.InternalMessageInfo

func (m *DeployResponse) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

func init() {
	proto.RegisterType((*DeployMessage)(nil), "deployproto.DeployMessage")
	proto.RegisterType((*DeployResponse)(nil), "deployproto.DeployResponse")
}

func init() { proto.RegisterFile("deployproto.proto", fileDescriptor_7e818a39b64e3e2b) }

var fileDescriptor_7e818a39b64e3e2b = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x4a, 0x03, 0x41,
	0x0c, 0x80, 0x5d, 0xad, 0x5b, 0x1b, 0x7f, 0xc0, 0x1c, 0x24, 0x54, 0x0f, 0xb2, 0x27, 0xf1, 0xd0,
	0x83, 0xbe, 0x82, 0x27, 0xc1, 0x4b, 0xbd, 0x79, 0x4b, 0x67, 0x83, 0x2c, 0x74, 0x67, 0x96, 0xc9,
	0x76, 0xa1, 0xcf, 0xe9, 0x0b, 0xc9, 0x4c, 0x76, 0xb1, 0x42, 0x2f, 0x33, 0xf9, 0xf2, 0x85, 0x84,
	0x04, 0x6e, 0x6b, 0xe9, 0xb6, 0x61, 0xdf, 0xc5, 0xd0, 0x87, 0x55, 0x7e, 0xf1, 0xf2, 0x20, 0x55,
	0xfd, 0x14, 0x70, 0xfd, 0x96, 0xf9, 0x43, 0x54, 0xf9, 0x5b, 0x10, 0x61, 0xe6, 0xb9, 0x15, 0x2a,
	0x1e, 0x8b, 0xa7, 0xc5, 0x3a, 0xc7, 0xf8, 0x00, 0x8b, 0xf4, 0x6b, 0xc7, 0x4e, 0xe8, 0x34, 0x8b,
	0xbf, 0x04, 0x12, 0xcc, 0x07, 0x89, 0xda, 0x04, 0x4f, 0x67, 0xd9, 0x4d, 0x88, 0x77, 0x50, 0xd6,
	0xa1, 0xe5, 0xc6, 0xd3, 0x2c, 0x8b, 0x91, 0xd2, 0x0c, 0x27, 0x7e, 0xa0, 0x73, 0x9b, 0x91, 0xe2,
	0x54, 0xab, 0x3d, 0xf7, 0x3b, 0xa5, 0xd2, 0x6a, 0x8d, 0x52, 0x77, 0xdd, 0xb5, 0x2d, 0xc7, 0x3d,
	0xcd, 0xad, 0xfb, 0x88, 0xc9, 0x88, 0xe7, 0xcd, 0x56, 0x6a, 0xba, 0x30, 0x33, 0x62, 0xf5, 0x0c,
	0x37, 0xb6, 0xd4, 0x5a, 0xb4, 0x0b, 0x5e, 0xc5, 0xba, 0x38, 0x27, 0xaa, 0xe3, 0x62, 0x13, 0xbe,
	0x7c, 0xc1, 0x95, 0xd5, 0x36, 0x9e, 0xfb, 0x10, 0xf1, 0x7d, 0x3a, 0xc8, 0xa7, 0xc4, 0xa1, 0x71,
	0x82, 0xcb, 0xd5, 0xe1, 0x0d, 0xff, 0x1d, 0x6b, 0x79, 0x7f, 0xc4, 0x4d, 0x33, 0xab, 0x93, 0x4d,
	0x99, 0xf3, 0xaf, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x43, 0x3b, 0xcb, 0x86, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeployinatorClient is the client API for Deployinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeployinatorClient interface {
	DeployService(ctx context.Context, in *DeployMessage, opts ...grpc.CallOption) (*DeployResponse, error)
}

type deployinatorClient struct {
	cc *grpc.ClientConn
}

func NewDeployinatorClient(cc *grpc.ClientConn) DeployinatorClient {
	return &deployinatorClient{cc}
}

func (c *deployinatorClient) DeployService(ctx context.Context, in *DeployMessage, opts ...grpc.CallOption) (*DeployResponse, error) {
	out := new(DeployResponse)
	err := c.cc.Invoke(ctx, "/deployproto.Deployinator/DeployService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployinatorServer is the server API for Deployinator service.
type DeployinatorServer interface {
	DeployService(context.Context, *DeployMessage) (*DeployResponse, error)
}

// UnimplementedDeployinatorServer can be embedded to have forward compatible implementations.
type UnimplementedDeployinatorServer struct {
}

func (*UnimplementedDeployinatorServer) DeployService(ctx context.Context, req *DeployMessage) (*DeployResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployService not implemented")
}

func RegisterDeployinatorServer(s *grpc.Server, srv DeployinatorServer) {
	s.RegisterService(&_Deployinator_serviceDesc, srv)
}

func _Deployinator_DeployService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployinatorServer).DeployService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deployproto.Deployinator/DeployService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployinatorServer).DeployService(ctx, req.(*DeployMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Deployinator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "deployproto.Deployinator",
	HandlerType: (*DeployinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployService",
			Handler:    _Deployinator_DeployService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deployproto.proto",
}
