cenv: dev
cid: place-1
clusterDomain: cluster.local
current_versions_file: some/path/versions.yaml
deployments:
  namespaces:
    - name: kube-system
      services:
        - chart: myhelmrepo/bob
          version: 5
        - chart: myhelmrepo/joe
          version: 10
    - name: othernamespace
      services:
      - chart: myhelmrepo/bob1
      - chart: myhelmrepo/steve1
        deployertype: newawesomedeployer
