local:andrew:
  clusterDomain: cluster.andrew.local
  current_versions_file: dev/versions.yaml
  services:
    namespaces:
      kube-system:
      - chart: weavelab/cluster-status
      - chart: weavelab/traefik
      ops:
      - chart: weavelab/alertmanager
      - chart: weavelab/etcd3
      - chart: weavelab/grafana
      - chart: weavelab/kibana
      - chart: weavelab/node-exporter
      - chart: weavelab/postgresql-internal
      - chart: weavelab/prometheus
      - chart: weavelab/redis
